### ISSUE TITLE
Multi-instrument SF2s reset to instrument in index 0 in the UI when closing and reopening the plugin window in Reaper

### ISSUE THREAD

**Issue by onlyforanonemails** [brummer10/Fluida.lv2#31] opened 2024-01-28 15:21 UTC
Tested on Linux Mint 21.3 (Cinnamon desktop), Reaper 7.07, Fluida 0.9.2.

If you have a multi-insturment SF2 loaded in Fluida in Reaper, the instrument index in the GUI seems to mostly (but not always) revert to the one in index 0, even though the correct instrument keeps playing.

In the below video I'm using the "General User GS" SF2 ( https://schristiancollins.com/generaluser.php ), the "HonkyTonk" instrument. Most of the time when closing the plugin window and reopening, it reverts to the instrument at index 0 which is "Stereo Grand". Later in the video I show the same thing happening when choosing the instrument " Marimba".
https://imgur.com/a/wABaFvM

Unlike the issue mentioned here,  https://github.com/brummer10/Fluida.lv2/issues/18 , for me it does not show None as current path, it shows the correct path to the SF2 file.

**Comment by brummer10** [comment] 2024-01-28 15:47
That's strange. I can't reproduce it. Here it works as expected. 
https://i.imgur.com/dyPEYP6.gif
Do you use the pre-build binary or do you build it yourself? In case you build yourself, please update to the latest git version, as that is what I use here.

**Comment by onlyforanonemails** [comment] 2024-01-28 19:55
I'm using the latest Linux 64 bit binary from github, not custom compiled ( this one: https://github.com/brummer10/Fluida.lv2/releases/download/v0.9.2/Fluida.lv2-v0.9.2-linux-x86_64.tar.xz  )
I extract the folder "Fluida.lv2" to "home/.lv2".

Reaper is flatpak version from Flathub, version 7.09.
This may also matter: I'm using evaluation version of Reaper, not purchased, maybe this has an effect. I'm still deciding between staying with FL Studio on Windows or if I can move my workflow to Linux.

You may also notice our Fluida font seems to be different as well. 
Any ideas?

**Comment by brummer10** [comment] 2024-01-29 05:24
Fluida using the "Sans" font set. When that isn't installed it fail back to whatever it found. You may install the "Sans" font set from your package manager to get rid of this _ugly_  font.

Also, could it be that you've a MIDI keyboard connected to Reaper which send MIDI clock? I know that some hosts have issues with LV2 atom ports when a MIDI clock is running. So it may be related to this issue https://github.com/brummer10/Fluida.lv2/issues/19

**Comment by onlyforanonemails** [comment] 2024-01-29 12:22
Have you tried the plugin on a flatpak version of Reaper? That may be the problem. The plugin may not be given access to the fonts folder of the system by the DAW. Because I seem to have the needed fonts:
![1](https://github.com/brummer10/Fluida.lv2/assets/157605035/a8b8e1c9-431f-48e6-aadd-f2648aa27242)
![2](https://github.com/brummer10/Fluida.lv2/assets/157605035/a6a68e9e-8ee1-4421-bc7b-6e5a1acc51e4)

There seems to be two solutions here:

1) Bundle a font file with the plugin itself
AND/OR:
2) Have a list of fonts to fallback to in case the plugin fails to find the one it wanted. As you can see if you let it fallback to whatever it finds first, the results can be pretty unusable.

>Also, could it be that you've a MIDI keyboard connected to Reaper which send MIDI clock?

No I don't. I do have a MIDI keyboard but it's not connected right now/for about a month/

**Comment by brummer10** [comment] 2024-01-29 12:31
Maybe you switch away from the flatpack version of Reaper. Why do you use it from flatpack anyway? 
I use as well the evolution version of Reaper, just download the binary, unpack it and run it from the download folder without any installation needed. 
I can't see any gain in using Reaper  nor any other host at all, from flatpack. That is always a source of trouble which could easily be avoided.

**Comment by onlyforanonemails** [comment] 2024-01-29 12:40
I won't speak for myself but in general:
Flatpaks are almost always up-to-date, quicker to install since available from most software managers, and in case of Reaper, require zero fiddling in command line. But we can ignore all this:

The general rule in software development is you don't offer software that limits user's choices for an unnecessary reason.
It's not for us to decide what is or isn't better to use. You can decide people should use your software this or that way, but at the end of the day you're artifically limiting usefulness of your software to a subset of your users and potentially reducing the number of users, and for what really?

Again, I'm not speaking for myself, I could just move to a non-flatpak version, even though I'd prefer not to. But all this may be avoidable if the dev lets the users make their own choices, I don't think this is a good road to go down.

**Comment by brummer10** [comment] 2024-01-29 13:25
> I'm not sure what the issue is with including a freefont file, they seem pretty small.

A plugin is loaded into the addressing space of the host. If, the same font is already loaded by the host, that may lead to symbol clashes.  Hence, that is the reason why some stuff needs to be shared.

> I'll need to get access to it and try first.

Yes please, try it. You'll surprised how easy Reaper makes it for you to use the binary.

**Comment by onlyforanonemails** [comment] 2024-01-29 13:29
>A plugin is loaded into the addressing space of the host. If, the same font is already loaded by the host, that may lead to symbol clashes. Hence, that is the reason why some stuff needs to be shared.

Sounds like you can alter the name of the font file to avoid that.

>Yes please, try it. You'll surprised how easy Reaper makes it for you to use the binary.

To clarify, I've used the Reaper binary from the site before, the advatnages of flatpak I listed still stand.

**Comment by brummer10** [comment] 2024-01-29 13:37
I'm sorry, but that wont happen. I maintain a couple of plugs using libxputty as GUI back-end. Some of them needs a other fonts, for example to display Note names, back that all in, rename all the symbols, is, in my view a overkill. 

You know that the issue could be solved easily as well by flatpack, by just add the font to the pack. So, it's not me who limit the user, it's the flatpack pack which limit your access to your system.

**Comment by onlyforanonemails** [comment] 2024-01-29 13:40
No I meant renaming the file name of the freefont file stored locally in the .lv2 plugin folder.

You can blame flatpak all you want but the end user experience is all that should matter.

And again, other VST/LV2 plugins seem to work fine. So we could discuss the APIs involved and the technology involved, but at the end of the day it wouldn't change the user experience with your software.

**Comment by onlyforanonemails** [comment] 2024-01-29 14:23
Look, I kept my calm and engaged in this discussion but  the bottom line is all you're doing here is trying to win an argument instead of making software better:

1) Other plugins work just fine, therefore this is not an inherent Flatpak issue. I've explain this already and still see you bringing it up.
2) It's not for you to decide if users should be using flatpak or non-flatpak versions of their DAWs.  I've explain this already and still see you bringing it up.

Regular users will see a problem with the software that makes it unusable for them and move on to other options. I don't see a need in contributing more feedback to a project where the dev finds this fine.
Expecting users to use sofware they way you personally prefer and to limit themselves that way is arrogant, impractical and completrely against the pilosophy of "free" sofware.
Good luck.

**Comment by brummer10** [comment] 2024-01-29 14:54
I don't want to win anything. I said that this is a minor issue and that I don't going to fix it. 
I explained to you that implementing a font file in a plugin isn't trivial, but you ignore my claims.

It seems you misunderstood how open software works.  I provide the source code. You have a issue. Fix it in the source and provide a pull request. Then I check it and decide if I would implement it or not. If not, you are free to maintain a fork with your own version which provide the fix you mean is useful. That is what Open Source is about. I'm not here to follow all your suggestions and fulfil your wishes. 

However, as you seems to loos your interest in Fluida, I close this issue now.

**Closed by brummer10** 2024-01-29 14:54 UTC

**Comment by onlyforanonemails** [comment] 2024-01-29 18:11
"I'm not here to follow all your suggestions and fulfil your wishes."

Yep, you prove my point here. You're here to provide software people will actually want to use. If the software has a bug or issue, you can either determine ways to fix it or ignore the issues and sweep them under the rug, which is precisely what you're doing here. Well then, you're keeping it bad on purpose and we don't have to use your software or engage in a discussion with you either. Simple.

**Comment by brummer10** [comment] 2024-01-29 18:39
This issue is closed. Open a new one if you want, but here, your comments ain't make it true any more.
